### ISSUE TITLE
Design Home Feed

### ISSUE THREAD

**Issue by chihabam** [SpotMe-Mondayvile/spotme#65]
1. Design Card (Spots) 
2. Any functions fields or buttons in the wrapper of the cards
3. For future (filter sort)
4. Search button

**Comment by chihabam** [comment]
https://excalidraw.com/#json=1ZXjzJrQCYPb9YDuSLTw_,7cw-zk9SZnhP_NcdssabIg

**Comment by chihabam** [comment]
![image](https://github.com/SpotMe-Mondayvile/spotme/assets/19781465/951a5628-a8c9-4443-bc35-e597f92bbe97)

**Comment by chihabam** [comment]
Search filter at the top

**Comment by princen02** [comment]
Home feed
