### ISSUE TITLE
Design Profile  Page for user

### ISSUE THREAD

**Issue by chihabam** [SpotMe-Mondayvile/spotme#66]
1. prof pic
2. bio
3. Highlights

**Comment by chihabam** [comment]
https://excalidraw.com/#json=1ZXjzJrQCYPb9YDuSLTw_,7cw-zk9SZnhP_NcdssabIg

**Comment by chihabam** [comment]
Dependent on #74

**Comment by SOULROSEGOLD** [comment]
![image](https://github.com/user-attachments/assets/777f17c7-9cc3-42fe-b6fe-efc8cc68f3b8)
![image](https://github.com/user-attachments/assets/3adbaa9c-4f9b-4588-a10e-2dc627a983c3)
https://excalidraw.com/#json=zmISH7HR2BgiIFb0WXBH_,8cH9mwN-6nJ7dr4hBVWCfQ

**Comment by SOULROSEGOLD** [comment]
Screenshots added, closing
