### ISSUE TITLE
Design user profile for Users(self)

### ISSUE THREAD

**Issue by chihabam** [SpotMe-Mondayvile/spotme#74]
1.  Change view Access between viewers, friends, and the owner of the account

**Comment by chihabam** [comment]
https://excalidraw.com/#room=2a6f6d360b74a3a27169,-N4ZpYJvF3FZeHfUvX8gCg

**Comment by SOULROSEGOLD** [comment]
Added variations in excalidraw for different locs for pfp, and a tabbed version for "stats" and spot history

https://excalidraw.com/#json=PXfNkRjDtvlc3pyunzrHV,9sqUm42krjgn8sXoA2XlNw

**Comment by SOULROSEGOLD** [comment]
![image](https://github.com/user-attachments/assets/55b9a689-2801-4fe5-a8bf-6fefefb5c219)
https://excalidraw.com/#json=T-BVyxJkCFsXlw9ZrSGsb,ckDzTMM1onvPCBnxE8HMdw
![image](https://github.com/user-attachments/assets/435197eb-8f37-49d8-932a-e849a9b57d4f)

completed.
